name: 'Anti Virus scan'
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo URI to scan (user/repo)'
        required: true
      packagename:
        description: 'Package name'
        required: true

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:
  clamav:
    name: ClamAV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository:  ${{ github.event.inputs.repo }}

      - name: Git AV Scan
        run: |
          clamav_output='scan.log'
          docker run --rm --mount type=bind,source=/home/runner/work/dispatcher-action/dispatcher-action,target=/scandir clamav/clamav:latest clamscan --recursive --log=/scandir/$clamav_output /scandir
          hsudo sed '/^\s*$/d' $clamav_output | awk -vmax="$(sudo cat $clamav_output | wc -l)" -F: 'BEGIN{print "{"} NR>1{gsub(/^ /, "", $2); printf "%s", "\042"$1"\042:\042"$2"\042"; if (NR<max-3) {print ","}else{print ""}}; END{print "}"}' > scan.json
        
      - name: AntiVirus results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.packagename }}-av
          path: scan.json
          if-no-files-found: ignore
