# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: dispatcher

on: [workflow_dispatch,push]

env:
    GH_TOKEN: ${{ secrets.GH_CRAWLER_TOKEN }}

permissions: read-all

jobs:
  dispatch:
    permissions:
      contents: read # for actions/checkout to fetch code
    name: Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Loop
        run: |
          mapfile -t array < listRepos.csv
          
          for i in "${array[@]}"
          do
              replace="https://github.com/"
              repo="${i//${replace}/''}"
              
              replace='/'
              name="${repo//${replace}/' in '}" 
              echo $'{"repo":"'${repo}'", "packagename":"'${name}'"}'
              echo $'{"repo":"'${repo}'", "packagename":"'${name}'"}' | gh workflow run packagescan.yml --json
          done
          
