
name: 'Checkmarx'
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo URL to scan'
        required: true
      packagename:
        description: 'Package name'
        required: true
permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:

    checkmarx:
      permissions:
        contents: read # for actions/checkout to fetch code
      name: Dispatch
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        with:
          repository: ${{ github.event.inputs.repo }}
      
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@2.0.9
        with:
          # Provide the AST portal URL
          base_uri: 'https://eu.ast.checkmarx.net/'
          # Provide the Tenant for AST portal URL
          cx_tenant: 'axago-fr54gt'
          # Client ID for AST portal authentication
          cx_client_id: 'Github-Action'
          # Secret key for AST portal authentication
          cx_client_secret: ${{secrets.CHECKMARX_SECRET}}
          # Select a Checkmarx Project Name
          project_name: '${{ github.event.repository.name }}'
          # Additional CLI arguments
          additional_params: '--file-filter !readme --report-format sarif --output-name results'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.sarif
