name: 'Secret Scan'
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repo URL to scan'
        required: true
      packagename:
        description: 'Package name'
        required: true

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: false

jobs:

# secret discovery trufflehog
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
          repository:  ${{ github.event.inputs.repo }}

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.23.1
        id: get_secret_scan
        with:
          path: .
          base: main # Start scanning from here (usually main branch)
          extra_args: --no-update --json

      - name: Insight of results
        run: |
          ls

      - name: Archive Trufflehog results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.packagename }}-secrets
          path: trufflehogresults.json
          if-no-files-found: ignore

#secret discovery
  gitleaks-scan:
      name: gitleaks
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
            repository:  ${{ github.event.inputs.repo }}

        - uses: gitleaks/gitleaks-action@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false

        - name: Gitleaks results
          uses: actions/upload-artifact@v3
          with:
            name: ${{ github.event.inputs.packagename }}-secrets
            path: results.sarif
            if-no-files-found: ignore
